# Generated by Django 5.1.1 on 2024-11-16 09:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリー名')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='性別')),
            ],
            options={
                'verbose_name': '性別',
                'verbose_name_plural': '性別',
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='注文タイプ')),
            ],
            options={
                'verbose_name': '注文タイプ',
                'verbose_name_plural': '注文タイプ',
                'db_table': 'order_types',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='時間帯')),
            ],
            options={
                'verbose_name': '時間帯',
                'verbose_name_plural': '時間帯',
                'db_table': 'time_slots',
            },
        ),
        migrations.CreateModel(
            name='WeatherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='天気')),
            ],
            options={
                'verbose_name': '天気',
                'verbose_name_plural': '天気',
                'db_table': 'weather_types',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='価格')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='data.category')),
            ],
            options={
                'verbose_name': 'メニューアイテム',
                'verbose_name_plural': 'メニューアイテム',
                'db_table': 'menu_items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='注文ID')),
                ('timestamp', models.DateTimeField(verbose_name='注文日時')),
                ('total_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計金額')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='割引額')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.gender', verbose_name='性別')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.ordertype', verbose_name='注文タイプ')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.timeslot', verbose_name='時間帯')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.weathertype', verbose_name='天気')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
                'db_table': 'orders',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='注文アイテムID')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='価格')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.menuitem', verbose_name='メニューアイテム')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data.order', verbose_name='注文')),
            ],
            options={
                'verbose_name': '注文項目',
                'verbose_name_plural': '注文項目',
                'db_table': 'order_items',
            },
        ),
    ]
